//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1_BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctlophp
    {
        public string MaLTM { get; set; }
        public string MaLHP { get; set; }
    
        public virtual lophocphan lophocphan { get; set; }
        public virtual lopmonhoc lopmonhoc { get; set; }
        public virtual lophocphan lophocphan1 { get; set; }
        public virtual lopmonhoc lopmonhoc1 { get; set; }
    }
}
