//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1_BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Diem
    {
        [Key, Column(Order = 1)]

        public string MaSV { get; set; }


        [Key, Column(Order = 2)]
        public string MaMon { get; set; }

        

        
        public double Diem1 { get; set; }
        
    
        [ForeignKey("MaMon")]
        public virtual mon mon { get; set; }
        [ForeignKey("MaSV")]
        public virtual sinhvien sinhvien { get; set; }
    }
}
