//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1_BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gv_mon
    {
        public string MaGV { get; set; }
        public string MaMon { get; set; }
    
        public virtual giangvien giangvien { get; set; }
        public virtual giangvien giangvien1 { get; set; }
        public virtual mon mon { get; set; }
        public virtual mon mon1 { get; set; }
    }
}
