//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1_BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kehoachgiangday
    {
        public string MaKHGD { get; set; }
        public string BaiHocDK { get; set; }
        public string DiaDiemDK { get; set; }
        public Nullable<System.DateTime> ThoiGianDK { get; set; }
        public string MaGV { get; set; }
    
        public virtual giangvien giangvien { get; set; }
    }
}
