//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1_BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lophocphan
    {
        public string MaLHP { get; set; }
        public string TenLopHP { get; set; }
        public string MaTGH { get; set; }
    
        public virtual ctlophp ctlophp { get; set; }
        public virtual ctlophp ctlophp1 { get; set; }
        public virtual thoigianhoc thoigianhoc { get; set; }
    }
}
