//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1_BTL_CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_cnpm_v3_1Entities : DbContext
    {
        public db_cnpm_v3_1Entities()
            : base("name=db_cnpm_v3_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ctlophp> ctlophps { get; set; }
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<giangvien> giangviens { get; set; }
        public virtual DbSet<gv_mon> gv_mon { get; set; }
        public virtual DbSet<kehoachgiangday> kehoachgiangdays { get; set; }
        public virtual DbSet<khoa> khoas { get; set; }
        public virtual DbSet<lichtrinhthucte> lichtrinhthuctes { get; set; }
        public virtual DbSet<lophocphan> lophocphans { get; set; }
        public virtual DbSet<lopmonhoc> lopmonhocs { get; set; }
        public virtual DbSet<mon> mons { get; set; }
        public virtual DbSet<nganh> nganhs { get; set; }
        public virtual DbSet<sinhvien> sinhviens { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<thoigianhoc> thoigianhocs { get; set; }
    }
}
